export const MathcPath = {
  'admin': 'Админ панель',
  'main': 'Главная',
  'ppm': 'Пункт самовывоза',
  'employees': 'Сотрудники',
  'customers': 'Покупатели',
  'employee': 'Сотрудник',
  'edit-texts': 'Редактирование текстов',
  'customer': 'Покупатель',
  'card-lists': 'Каталог карточек',
  'structure-catalog': 'Структура каталога',
  'terminal-owners': 'Собственники терминалов',
  'terminals': 'Терминалы',
  'card': 'Карточка',
  'preview': 'Предпросмотр',
  'promo-banners': 'Промо баннеры',
  'pickup-points': 'Пункты самовывоза',
  'pickup-points-owner': 'Собственник ПС',
  'add-pickup-points-owner': 'Добавление собственника ПС',
  'print-preparation': 'Подготовка печати',
  'print-process': 'Процесс печати',
  'orders': 'Заказы',
  'order': 'Заказ',
  'text-pages': 'Текстовые страницы',
  'blog-posts': 'Блог',
  'printers': 'Принтеры',
  'legal-entities': 'Юридические лица',
  'card-number-print-templates': "Шаблоны печати номеров карточек",
  'list': "Список",
  'assign': "Назначение",
};
